apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: jupyter-frontendconfig
  namespace: jupyter
spec:
  redirectToHttps:
    enabled: true                # force HTTP -> HTTPS
